version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11

    commands:
      - pip install -r requirements.txt

  build:
    commands:
      - python -m sphinx.ext.apidoc -o docs app --force
      - python -m sphinx -b html docs docs/_build/html

  post_build:
    commands:
      - aws s3 cp docs/_build/html s3://$DOC_BUCKET/ --recursive
      - echo "Deployment completed successfully"